### ISSUE TITLE
profiles (details)

### ISSUE THREAD

**Issue by fridashlmn** [fridashlmn/roomie#2]
## Value statement
As a **user** 
I need **a detailed view of my roommates stats** 
so that **I have an overview of the necessary information** .

## Description
Detailed profiles of every roommate with his/her roommate stats 
<img width="332" alt="Screenshot 2019-11-22 at 20 27 39" src="https://user-images.githubusercontent.com/55835559/69455107-f287cc80-0d67-11ea-86a4-7be8bc14e64a.png">

## Acceptance criteria
- [ ] styling according to sketch design
- [ ] At least 2 exemplary profiles have to be integrated
- [ ] Stats include name, duration of stay, room, rent, deposit and belongings

## Tasks
- [ ] Create profiles.json for exemplary profiles
- [ ] Create profile_details component and Add to App 
- [ ] Testing

## Size
small
