### ISSUE TITLE
contracts (default)

### ISSUE THREAD

**Issue by fridashlmn** [fridashlmn/roomie#22]
## Value statement - a requirement, not a solution
As a **user** 
I need **an empty contracts page at the beginning** 
so that **I know it's empty and I have to add my contracts** 

## Description 
Default page with text that leads the user to add contracts.
Design should be similar to the profile default page.

## Acceptance criteria
 - [ ] Is shown when the contracts.json is empty
 - [ ] Placeholder picture (free)
 - [ ] "add new contract" button - doesn't have to be interactive yet

## Tasks
- [ ]  Add contracts_default component and Add to App
- [ ]  Create button component
 - [ ] Add styling
 - [ ] Testing with empty contracts.json file

## Size
small
