### ISSUE TITLE
contracts (addnewcontract)

### ISSUE THREAD

**Issue by fridashlmn** [fridashlmn/roomie#23]
## Value statement
As a **user** 
I need **a contracts form** 
so that **I can add new contracts** 

## Description
Form to add new contracts.
"Add new contract" button should be on the contracts default page and the contracts teaser page.

## Acceptance criteria
- [ ] Form should include all keys to the profile details page
- [ ] Styling similar to the profiles form
- [ ] Submit button

## Tasks
- [ ]  Add "Add new roomie" button to the profile teaser page
- [ ]  Button should direct to the new page
 - [ ] Add new component for the ProfileForm and Add to App
 - [ ] Build form and add styling
- [ ] Testing

## Size
small
