### ISSUE TITLE
profiles (teaser)

### ISSUE THREAD

**Issue by fridashlmn** [fridashlmn/roomie#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **an overview of the profiles** 
so that **I can quickly navigated to the profile I'm looking for**. 

## Description
A list of teasers for every profile (name and duration of stay) which reveals on click the profile details
<img width="333" alt="Screenshot 2019-11-22 at 20 27 58" src="https://user-images.githubusercontent.com/55835559/69455095-ea2f9180-0d67-11ea-8193-c11c22bc73b5.png">

## Acceptance criteria
- [ ] styling according to sketch design
- [ ] Detailed view can either be hidden/collapsed or on a new site
- [ ] Transition from teaser to detailed view should be animated
- [ ] Profile details and teaser have to toggle (button / x / or else)

## Tasks
- [ ] Create profile_teaser component and Add to App
- [ ] Add styling and animation
- [ ] Testing

## Size
small
